### PR TITLE
Solve conflict with capistrano-sidekiq

### PR DESCRIPTION
**Pull request by coderliu**
* Prefix methods to distinguish with methods defined by capistrano-sidekiq
* Move methods into `Capistrano::Sneakers::HelperMethods` to keep rake file clean, this is official way  [ref](https://github.com/capistrano-plugins/capistrano-unicorn-nginx/blob/master/lib/capistrano/tasks/nginx.rake)

### CODE REVIEW

**Comment by coderliu** [comment]
I have tried to isolate methods without prefix, by I can not find a way.

Below is the nearest way
``` ruby
# lib/blog_post_creator.rb
module BlogPostCreator
  def self.create_default_blog_post
    puts "Generating a default blog post"
  end

  def self.save(post)
    puts "Saving default blog post"
  end
end

# lib/tasks/create_blog_post_task.rake
require 'lib/blog_post_creator' # require and no include

desc 'Create and save a new blog post'
task :create_blog_post do
  blog_post = BlogPostCreator.create_default_blog_post # invoke as ClassMethod
  BlogPostCreator.save(blog_post)
end
```
but methods like below which rely on some SSHKit context will fail.

``` ruby
def sneakers_pid_files
  sneakers_roles = Array(fetch(:sneakers_roles))
  sneakers_roles.select! { |role| host.roles.include?(role) }
  sneakers_roles.flat_map do |role|
    processes = fetch(:sneakers_processes)
    if processes == 1
      fetch(:sneakers_pid)
    else
      Array.new(processes) { |idx| fetch(:sneakers_pid).gsub(/\.pid$/, "-#{idx}.pid") }
    end
  end
end
```

```
SSHKit::Runner::ExecuteError: Exception while executing as deploy@hostname: undefined local variable or method `host' for Capistrano::Sneakers::HelperMethods:Module
```

Anyway, solve the conflict and make this gem work properly with capistrano-sidekiq is necessary. That's why I create this imperfect patch.

**Comment by coderliu** [comment]
Any response? @inventionlabsSydney 

THE LATEST RELEASE OF THIS GEM ON RUBYGEMS.ORG CAN NOT WORK WITH CAPISTRANO-SIDEKIQ TOTALLY.

As a maintainer, you have responsibility to keep it work properly. If you can not, you should reminder user existent of this conflict with `capistrano-sidekiq` and ask for helper from community.

**Comment by inventionlabsSydney** [comment]
Hi @coderliu I'm currently busy and cannot attend to this just yet as I am on travels. I'll be able to look friday.

**Comment by coderliu** [comment]
@inventionlabsSydney Sorry for interruption. Enjoy your travels 😆

**Comment by Tensho** [comment]
@coderliu Thanks for your contribution, I'll take a look. Please add problem description to PR or at least refer to corresponding GitHub Issue the next time 🙇

**Comment by Tensho** [comment]
Are you going to add the same to `capistrano-sidekiq`? We would like to keep the code of these 2 gems as similar as possible (consistent). It's much much easier to switch between them if we experience the same problem in both.

**Comment by coderliu** [comment]
@Tensho I will submit a issue to `capistrano-sidekiq`. If this kind of change is acceptable to its  maintainer, I will create a pull request.

**Comment by coderliu** [comment]
@Tensho Here is problem description https://github.com/inventionlabsSydney/capistrano-sneakers/commit/e5ffbb6615a26f75cca1132ddac30cdcbdc3f942#commitcomment-29915900

**Comment by coderliu** [comment]
@Tensho I encounter the `sneakers instance variables` problem three weeks ago 🙊. It looks like the  document of sneakers need some improvement.

**Comment by Tensho** [comment]
@inventionlabsSydney Karl, could we merge this and bump the version please?

**Pull request merged**
